In [1]:
import pandas as pd

In [2]:
f = '../data_dump/gencode.vM32.annotation.gtf.gz'
df = pd.read_csv(f, sep="\t", skiprows=5, header=None)
df

,0,1,2,3,4,5,6,7,8
0,chr1,HAVANA,gene,3143476,3144545,.,+,.,"gene_id ""ENSMUSG00000102693.2""; gene_type ""TEC..."
1,chr1,HAVANA,transcript,3143476,3144545,.,+,.,"gene_id ""ENSMUSG00000102693.2""; transcript_id ..."
2,chr1,HAVANA,exon,3143476,3144545,.,+,.,"gene_id ""ENSMUSG00000102693.2""; transcript_id ..."
3,chr1,ENSEMBL,gene,3172239,3172348,.,+,.,"gene_id ""ENSMUSG00000064842.3""; gene_type ""snR..."
4,chr1,ENSEMBL,transcript,3172239,3172348,.,+,.,"gene_id ""ENSMUSG00000064842.3""; transcript_id ..."
...,...,...,...,...,...,...,...,...,...
1903937,chrM,ENSEMBL,transcript,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; transcript_id ..."
1903938,chrM,ENSEMBL,exon,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; transcript_id ..."
1903939,chrM,ENSEMBL,gene,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; gene_type ""Mt_..."
1903940,chrM,ENSEMBL,transcript,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; transcript_id ..."
1903941,chrM,ENSEMBL,exon,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; transcript_id ..."

In [3]:
dfg = df[df[2] == 'gene'].copy()
dfg

,0,1,2,3,4,5,6,7,8
0,chr1,HAVANA,gene,3143476,3144545,.,+,.,"gene_id ""ENSMUSG00000102693.2""; gene_type ""TEC..."
3,chr1,ENSEMBL,gene,3172239,3172348,.,+,.,"gene_id ""ENSMUSG00000064842.3""; gene_type ""snR..."
6,chr1,HAVANA,gene,3276124,3741721,.,-,.,"gene_id ""ENSMUSG00000051951.6""; gene_type ""pro..."
24,chr1,HAVANA,gene,3322980,3323459,.,+,.,"gene_id ""ENSMUSG00000102851.2""; gene_type ""pro..."
27,chr1,HAVANA,gene,3435954,3438772,.,-,.,"gene_id ""ENSMUSG00000103377.2""; gene_type ""TEC..."
...,...,...,...,...,...,...,...,...,...
1903921,chrM,ENSEMBL,gene,13552,14070,.,-,.,"gene_id ""ENSMUSG00000064368.1""; gene_type ""pro..."
1903928,chrM,ENSEMBL,gene,14071,14139,.,-,.,"gene_id ""ENSMUSG00000064369.1""; gene_type ""Mt_..."
1903931,chrM,ENSEMBL,gene,14145,15288,.,+,.,"gene_id ""ENSMUSG00000064370.1""; gene_type ""pro..."
1903936,chrM,ENSEMBL,gene,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; gene_type ""Mt_..."
1903939,chrM,ENSEMBL,gene,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; gene_type ""Mt_..."

In [4]:
dfg['gene_id']   = dfg[8].apply(lambda x: x.split(';')[0].split(' ')[1].strip('\"')) 
dfg['gene_name'] = dfg[8].apply(lambda x: x.split(';')[2].split(' ')[2].strip('\"'))
dfg

,0,1,2,3,4,5,6,7,8,gene_id,gene_name
0,chr1,HAVANA,gene,3143476,3144545,.,+,.,"gene_id ""ENSMUSG00000102693.2""; gene_type ""TEC...",ENSMUSG00000102693.2,4933401J01Rik
3,chr1,ENSEMBL,gene,3172239,3172348,.,+,.,"gene_id ""ENSMUSG00000064842.3""; gene_type ""snR...",ENSMUSG00000064842.3,Gm26206
6,chr1,HAVANA,gene,3276124,3741721,.,-,.,"gene_id ""ENSMUSG00000051951.6""; gene_type ""pro...",ENSMUSG00000051951.6,Xkr4
24,chr1,HAVANA,gene,3322980,3323459,.,+,.,"gene_id ""ENSMUSG00000102851.2""; gene_type ""pro...",ENSMUSG00000102851.2,Gm18956
27,chr1,HAVANA,gene,3435954,3438772,.,-,.,"gene_id ""ENSMUSG00000103377.2""; gene_type ""TEC...",ENSMUSG00000103377.2,Gm37180
...,...,...,...,...,...,...,...,...,...,...,...
1903921,chrM,ENSEMBL,gene,13552,14070,.,-,.,"gene_id ""ENSMUSG00000064368.1""; gene_type ""pro...",ENSMUSG00000064368.1,mt-Nd6
1903928,chrM,ENSEMBL,gene,14071,14139,.,-,.,"gene_id ""ENSMUSG00000064369.1""; gene_type ""Mt_...",ENSMUSG00000064369.1,mt-Te
1903931,chrM,ENSEMBL,gene,14145,15288,.,+,.,"gene_id ""ENSMUSG00000064370.1""; gene_type ""pro...",ENSMUSG00000064370.1,mt-Cytb
1903936,chrM,ENSEMBL,gene,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; gene_type ""Mt_...",ENSMUSG00000064371.1,mt-Tt
1903939,chrM,ENSEMBL,gene,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; gene_type ""Mt_...",ENSMUSG00000064372.1,mt-Tp

In [10]:
dfgbed = dfg[[0, 3, 4, 6, 'gene_id', 'gene_name',]].copy()
dfgbed['gid_short'] = dfgbed['gene_id'].apply(lambda x: x.split('.')[0])
dfgbed

,0,3,4,6,gene_id,gene_name,gid_short
0,chr1,3143476,3144545,+,ENSMUSG00000102693.2,4933401J01Rik,ENSMUSG00000102693
3,chr1,3172239,3172348,+,ENSMUSG00000064842.3,Gm26206,ENSMUSG00000064842
6,chr1,3276124,3741721,-,ENSMUSG00000051951.6,Xkr4,ENSMUSG00000051951
24,chr1,3322980,3323459,+,ENSMUSG00000102851.2,Gm18956,ENSMUSG00000102851
27,chr1,3435954,3438772,-,ENSMUSG00000103377.2,Gm37180,ENSMUSG00000103377
...,...,...,...,...,...,...,...
1903921,chrM,13552,14070,-,ENSMUSG00000064368.1,mt-Nd6,ENSMUSG00000064368
1903928,chrM,14071,14139,-,ENSMUSG00000064369.1,mt-Te,ENSMUSG00000064369
1903931,chrM,14145,15288,+,ENSMUSG00000064370.1,mt-Cytb,ENSMUSG00000064370
1903936,chrM,15289,15355,+,ENSMUSG00000064371.1,mt-Tt,ENSMUSG00000064371
1903939,chrM,15356,15422,-,ENSMUSG00000064372.1,mt-Tp,ENSMUSG00000064372

In [11]:
fout = '../data_dump/gencode.vM32.allgenes.bed'
dfgbed.to_csv(fout, sep="\t", header=False, index=False)

In [12]:
!head $fout

chr1	3143476	3144545	+	ENSMUSG00000102693.2	4933401J01Rik	ENSMUSG00000102693
chr1	3172239	3172348	+	ENSMUSG00000064842.3	Gm26206	ENSMUSG00000064842
chr1	3276124	3741721	-	ENSMUSG00000051951.6	Xkr4	ENSMUSG00000051951
chr1	3322980	3323459	+	ENSMUSG00000102851.2	Gm18956	ENSMUSG00000102851
chr1	3435954	3438772	-	ENSMUSG00000103377.2	Gm37180	ENSMUSG00000103377
chr1	3445779	3448011	-	ENSMUSG00000104017.2	Gm37363	ENSMUSG00000104017
chr1	3535200	3537508	-	ENSMUSG00000103025.2	Gm37686	ENSMUSG00000103025
chr1	3536810	3583776	+	ENSMUSG00000089699.2	Gm1992	ENSMUSG00000089699
chr1	3582674	3584730	-	ENSMUSG00000103201.2	Gm37329	ENSMUSG00000103201
chr1	3602018	3602943	+	ENSMUSG00000103147.2	Gm7341	ENSMUSG00000103147