In [1]:
import pandas as pd

In [2]:
f = './test_erna_data/mm10.gtf.gz'
df = pd.read_csv(f, sep='\t', skiprows=5, header=None,
                 # nrows=100,
                )
df

,0,1,2,3,4,5,6,7,8
0,chr1,HAVANA,gene,3073253,3074322,.,+,.,"gene_id ""ENSMUSG00000102693.1""; gene_type ""TEC..."
1,chr1,HAVANA,transcript,3073253,3074322,.,+,.,"gene_id ""ENSMUSG00000102693.1""; transcript_id ..."
2,chr1,HAVANA,exon,3073253,3074322,.,+,.,"gene_id ""ENSMUSG00000102693.1""; transcript_id ..."
3,chr1,ENSEMBL,gene,3102016,3102125,.,+,.,"gene_id ""ENSMUSG00000064842.1""; gene_type ""snR..."
4,chr1,ENSEMBL,transcript,3102016,3102125,.,+,.,"gene_id ""ENSMUSG00000064842.1""; transcript_id ..."
...,...,...,...,...,...,...,...,...,...
1872047,chrM,ENSEMBL,transcript,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; transcript_id ..."
1872048,chrM,ENSEMBL,exon,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; transcript_id ..."
1872049,chrM,ENSEMBL,gene,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; gene_type ""Mt_..."
1872050,chrM,ENSEMBL,transcript,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; transcript_id ..."
1872051,chrM,ENSEMBL,exon,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; transcript_id ..."

In [3]:
df[2].unique()

array(['gene', 'transcript', 'exon', 'CDS', 'start_codon', 'stop_codon',
       'UTR', 'Selenocysteine'], dtype=object)

In [4]:
dfg = df[df[2]=='gene']
dfg

,0,1,2,3,4,5,6,7,8
0,chr1,HAVANA,gene,3073253,3074322,.,+,.,"gene_id ""ENSMUSG00000102693.1""; gene_type ""TEC..."
3,chr1,ENSEMBL,gene,3102016,3102125,.,+,.,"gene_id ""ENSMUSG00000064842.1""; gene_type ""snR..."
6,chr1,HAVANA,gene,3205901,3671498,.,-,.,"gene_id ""ENSMUSG00000051951.5""; gene_type ""pro..."
24,chr1,HAVANA,gene,3252757,3253236,.,+,.,"gene_id ""ENSMUSG00000102851.1""; gene_type ""pro..."
27,chr1,HAVANA,gene,3365731,3368549,.,-,.,"gene_id ""ENSMUSG00000103377.1""; gene_type ""TEC..."
...,...,...,...,...,...,...,...,...,...
1872031,chrM,ENSEMBL,gene,13552,14070,.,-,.,"gene_id ""ENSMUSG00000064368.1""; gene_type ""pro..."
1872038,chrM,ENSEMBL,gene,14071,14139,.,-,.,"gene_id ""ENSMUSG00000064369.1""; gene_type ""Mt_..."
1872041,chrM,ENSEMBL,gene,14145,15288,.,+,.,"gene_id ""ENSMUSG00000064370.1""; gene_type ""pro..."
1872046,chrM,ENSEMBL,gene,15289,15355,.,+,.,"gene_id ""ENSMUSG00000064371.1""; gene_type ""Mt_..."
1872049,chrM,ENSEMBL,gene,15356,15422,.,-,.,"gene_id ""ENSMUSG00000064372.1""; gene_type ""Mt_..."

In [5]:
bed = dfg[[0,3,4]]
bed.to_csv('./test_erna_data/allgenebodies.bed', header=False, index=False, sep='\t')