In [13]:
import numpy as np
import pandas as pd
import os
import glob

In [4]:
pth = '/bigstore/binfo/mouse/Brain/FISH/MERFISH_Fang2022_Science_CTX'
!ls $pth

doi_10.5061_dryad.x3ffbg7mw__v10.zip
H18.06.006.MTG.250.expand.rep1.barcodes.csv.gz
H18.06.006.MTG.250.expand.rep1.features.csv
H18.06.006.MTG.250.expand.rep1.genes.csv
H18.06.006.MTG.250.expand.rep1.matrix.csv
H18.06.006.MTG.4000.expand.rep1.barcodes.csv.gz
H18.06.006.MTG.4000.expand.rep1.features.csv
H18.06.006.MTG.4000.expand.rep1.genes.csv
H18.06.006.MTG.4000.expand.rep1.matrix.csv
H18.06.006.MTG.4000.expand.rep2.barcodes.csv.gz
H18.06.006.MTG.4000.expand.rep2.features.csv
H18.06.006.MTG.4000.expand.rep2.genes.csv
H18.06.006.MTG.4000.expand.rep2.matrix.csv
H18.06.006.MTG.4000.expand.rep3.barcodes.csv.gz
H18.06.006.MTG.4000.expand.rep3.features.csv
H18.06.006.MTG.4000.expand.rep3.genes.csv
H18.06.006.MTG.4000.expand.rep3.matrix.csv
H19.30.001.STG.250.expand.rep1.barcodes.csv.gz
H19.30.001.STG.250.expand.rep1.features.csv
H19.30.001.STG.250.expand.rep1.genes.csv
H19.30.001.STG.250.expand.rep1.matrix.csv
H19.30.001.STG.4000.expand.rep1.barcodes.csv.gz
H19.30.001.STG.4000.expand.rep1.features.csv
H19.30.001.STG.4000.expand.rep1.genes.csv
H19.30.001.STG.4000.expand.rep1.matrix.csv
H19.30.001.STG.4000.expand.rep2.barcodes.csv.gz
H19.30.001.STG.4000.expand.rep2.features.csv
H19.30.001.STG.4000.expand.rep2.genes.csv
H19.30.001.STG.4000.expand.rep2.matrix.csv
H20.30.001.STG.250.unexpand.rep1.barcodes.csv.gz
H20.30.001.STG.250.unexpand.rep1.features.csv
H20.30.001.STG.250.unexpand.rep1.genes.csv
H20.30.001.STG.250.unexpand.rep1.matrix.csv
H20.30.001.STG.250.unexpand.rep2.barcodes.csv.gz
H20.30.001.STG.250.unexpand.rep2.features.csv
H20.30.001.STG.250.unexpand.rep2.genes.csv
H20.30.001.STG.250.unexpand.rep2.matrix.csv
H20.30.001.STG.4000.expand.rep1.barcodes.csv.gz
H20.30.001.STG.4000.expand.rep1.features.csv
H20.30.001.STG.4000.expand.rep1.genes.csv
H20.30.001.STG.4000.expand.rep1.matrix.csv
H20.30.001.STG.4000.expand.rep2.barcodes.csv.gz
H20.30.001.STG.4000.expand.rep2.features.csv
H20.30.001.STG.4000.expand.rep2.genes.csv
H20.30.001.STG.4000.expand.rep2.matrix.csv
H20.30.001.STG.4000.expand.rep3.barcodes.csv.gz
H20.30.001.STG.4000.expand.rep3.features.csv
H20.30.001.STG.4000.expand.rep3.genes.csv
H20.30.001.STG.4000.expand.rep3.matrix.csv
H22.26.401.MTG.250.unexpand.rep1.barcodes.csv.gz
H22.26.401.MTG.250.unexpand.rep1.features.csv
H22.26.401.MTG.250.unexpand.rep1.genes.csv
H22.26.401.MTG.250.unexpand.rep1.matrix.csv
H22.26.401.MTG.4000.expand.rep1.barcodes.csv.gz
H22.26.401.MTG.4000.expand.rep1.features.csv
H22.26.401.MTG.4000.expand.rep1.genes.csv
H22.26.401.MTG.4000.expand.rep1.matrix.csv
H22.26.401.MTG.4000.expand.rep2.barcodes.csv.gz
H22.26.401.MTG.4000.expand.rep2.features.csv
H22.26.401.MTG.4000.expand.rep2.genes.csv
H22.26.401.MTG.4000.expand.rep2.matrix.csv
mouse1.AUD_TEA_VIS.242.unexpand.barcodes.csv.gz
mouse1.AUD_TEA_VIS.242.unexpand.features.csv
mouse1.AUD_TEA_VIS.242.unexpand.genes.csv
mouse1.AUD_TEA_VIS.242.unexpand.matrix.csv
mouse2.AUD_TEA_VIS.242.unexpand.barcodes.csv.gz
mouse2.AUD_TEA_VIS.242.unexpand.features.csv
mouse2.AUD_TEA_VIS.242.unexpand.genes.csv
mouse2.AUD_TEA_VIS.242.unexpand.matrix.csv
README.txt
sample_metadata.csv

In [11]:
files = np.sort(glob.glob("mouse*", dir_fd=pth))
files

array(['mouse1.AUD_TEA_VIS.242.unexpand.barcodes.csv.gz',
       'mouse1.AUD_TEA_VIS.242.unexpand.features.csv',
       'mouse1.AUD_TEA_VIS.242.unexpand.genes.csv',
       'mouse1.AUD_TEA_VIS.242.unexpand.matrix.csv',
       'mouse2.AUD_TEA_VIS.242.unexpand.barcodes.csv.gz',
       'mouse2.AUD_TEA_VIS.242.unexpand.features.csv',
       'mouse2.AUD_TEA_VIS.242.unexpand.genes.csv',
       'mouse2.AUD_TEA_VIS.242.unexpand.matrix.csv'], dtype='<U47')

In [19]:
f = os.path.join(pth, "mouse1.AUD_TEA_VIS.242.unexpand.features.csv")
meta = pd.read_csv(f)
meta

,name,global.x,global.y,adjusted.x,adjusted.y,fov.x,fov.y,cluster_L1,cluster_L2,cluster_L3
0,fov_201_feature_1,-3408.476396,1289.825315,-3408.476396,1289.825315,1922.413292,164.049783,EXC,eL2/3.IT,eL2/3.IT.1
1,fov_202_feature_1,-3454.789690,1092.856622,-3454.789690,1092.856622,1497.520686,191.859933,EXC,eL2/3.IT,eL2/3.IT.1
2,fov_202_feature_11,-3441.307424,1128.932078,-3441.307424,1128.932078,1621.211194,522.827421,EXC,eL2/3.IT,eL2/3.IT.1
3,fov_202_feature_12,-3455.460129,1130.627496,-3455.460129,1130.627496,1491.369865,538.381719,EXC,eL2/3.IT,eL2/3.IT.1
4,fov_202_feature_14,-3419.537992,1144.648035,-3419.537992,1144.648035,1820.930753,667.010518,EXC,eL2/3.IT,eL2/3.IT.1
...,...,...,...,...,...,...,...,...,...,...
13217,fov_401_feature_73,-1339.942915,2556.751841,-1339.942915,2556.751841,716.298435,778.054607,lOGC,lOGC,lOGC
13218,fov_401_feature_8,-1298.422691,2507.721424,-1298.422691,2507.721424,1097.217925,328.234267,lASC,lASC,lASC
13219,fov_401_feature_85,-1401.446263,2640.863239,-1401.446263,2640.863239,152.047537,1549.718805,lOGC,lOGC,lOGC
13220,fov_401_feature_9,-1271.547703,2510.911698,-1271.547703,2510.911698,1343.777445,357.502832,lMGC,lASC,lASC
13221,fov_402_feature_28,-1405.109240,2751.135878,-1405.109240,2751.135878,118.442239,726.532007,lOGC,lOGC,lOGC

In [20]:
f = os.path.join(pth, "mouse1.AUD_TEA_VIS.242.unexpand.genes.csv")
genes = pd.read_csv(f)
genes

              name
0    1700022I11Rik
1    1810046K07Rik
2    5031425F14Rik
3    5730522E02Rik
4            Acta2
..             ...
237            Vtn
238           Vwc2
239          Wipf3
240          Wnt7b
241        Zfp804b

[242 rows x 1 columns]

In [21]:
f = os.path.join(pth, "mouse1.AUD_TEA_VIS.242.unexpand.matrix.csv")
mtx = pd.read_csv(f)
mtx