In [1]:
import pandas as pd
import numpy as np
import anndata as ad

# Metadata

In [2]:
f = '../data/candidate_genes_vincent_0316.xlsx'
df0 = pd.read_excel(f, sheet_name=0)
df1 = pd.read_excel(f, sheet_name=1)

print(df0.shape, df1.shape)

(103, 9) (13, 8)

In [3]:
df0

,Target Name,Not in Catatlog,Probe set size,HCR Amplifer to use with,Order (11/11/2021),Accession # (validated w/ CCDS),ABA Accession #,Order?,Unnamed: 8
0,Baz1a,NaN,20.0,B2,x - B2,NaN,NaN,y - B2,NaN
1,Agmat,NaN,20.0,"B2, B3",x - B3,NaN,NaN,NaN,NaN
2,Adamts2,NaN,20.0,"B1, B2, B3",x - B1,NaN,NaN,y - B1,NaN
3,Rrad,NaN,20.0,"B2, B3",NaN,NM_019662.3,NM_019662.1,y - B3,NaN
4,Trpc6,NaN,20.0,B1,x - B1,NaN,NaN,y - B1,NaN
...,...,...,...,...,...,...,...,...,...
98,Stard7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
99,Cldn5,NaN,NaN,NaN,NaN,NM_013805.3,NM_013805.4,Y - B5,NaN
100,Chrm3,Y,20.0,NaN,NaN,NM_033269,NaN,Y - B2,NaN
101,Whrn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,Stard8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df1

,Target Name,Not in Catatlog,Probe set size,HCR Amplifer to use with,Order (11/11/2021),Accession # (validated w/ CCDS),ABA Accession #,Order?
0,Slc1a3,Y,20.0,"B1, B2, B3, B4",NaN,NaN,NaN,NaN
1,Mertk,N,NaN,NaN,NaN,NaN,NaN,NaN
2,Rfx4,N,NaN,NaN,NaN,NaN,NaN,NaN
3,Clasp2,N,NaN,NaN,NaN,NaN,NaN,NaN
4,Ntrk2(TrkB),Y,20.0,"B2, B3, B4, B5",NaN,NaN,NaN,NaN
5,Chrdl1,N,NaN,NaN,NaN,NaN,NaN,NaN
6,Id3,Y,14.0,"B2, B3",NaN,NaN,NaN,NaN
7,Nrxn1,N,NaN,NaN,NaN,NaN,NaN,NaN
8,Il33,N,NaN,NaN,NaN,NaN,NaN,NaN
9,Scel,N,NaN,NaN,NaN,NaN,NaN,NaN
10,Cdh19,N,NaN,NaN,NaN,NaN,NaN,NaN
11,Pcdh9,N,NaN,NaN,NaN,NaN,NaN,NaN
12,Pcdhgc3,N,NaN,NaN,NaN,NaN,NaN,NaN

# Files

In [5]:
f = '../data/L23_VD.h5ad'
adata1 = ad.read(f, backed='r+')
adata1

AnnData object with n_obs Ã— n_vars = 21269 Ã— 19650 backed at '../data/L23_VD.h5ad'
    obs: 'batch', 'n_genes', 'percent_mito', 'n_counts', 'leiden', 'Doublet', 'Doublet Score', 'cluster', 'Class_broad', 'sample', 'Age', 'subclass', 'sample_new', 'layer', 'Type', 'Subclass', 'AgeType', 'Condition'
    var: 'gene_ids', 'feature_types', 'n_cells-0', 'highly_variable-0', 'means-0', 'mean-0', 'std-0', 'dispersions-P28_NR L2/3 A-0', 'dispersions_norm-P28_NR L2/3 A-0', 'dispersions-P28_NR L2/3 B-0', 'dispersions_norm-P28_NR L2/3 B-0', 'dispersions-P28_NR L2/3 C-0', 'dispersions_norm-P28_NR L2/3 C-0', 'n_cells-1', 'highly_variable-1', 'means-1', 'mean-1', 'std-1', 'dispersions-P38_NR L2/3 A-1', 'dispersions_norm-P38_NR L2/3 A-1', 'dispersions-P38_NR L2/3 B-1', 'dispersions_norm-P38_NR L2/3 B-1', 'dispersions-P38_NR L2/3 C-1', 'dispersions_norm-P38_NR L2/3 C-1', 'highly_variable-2', 'means-2', 'mean-2', 'std-2', 'dispersions-P28_DR L2/3 1-2', 'dispersions_norm-P28_DR L2/3 1-2', 'dispersions-P28_DR L2/3 2-2', 'dispersions_norm-P28_DR L2/3 2-2', 'dispersions-P28_DR L2/3 3-2', 'dispersions_norm-P28_DR L2/3 3-2', 'highly_variable-3', 'means-3', 'mean-3', 'std-3', 'dispersions-P38_DR L2/3 1-3', 'dispersions_norm-P38_DR L2/3 1-3', 'dispersions-P38_DR L2/3 2-3', 'dispersions_norm-P38_DR L2/3 2-3', 'dispersions-P38_DR L2/3 3-3', 'dispersions_norm-P38_DR L2/3 3-3', 'highly_variable-4', 'means-4', 'mean-4', 'std-4', 'dispersions-P28_DL L2/3 1-4', 'dispersions_norm-P28_DL L2/3 1-4', 'dispersions-P28_DL L2/3 2-4', 'dispersions_norm-P28_DL L2/3 2-4', 'dispersions-P28_DL L2/3 3-4', 'dispersions_norm-P28_DL L2/3 3-4'
    obsm: 'X_harmony', 'X_pca', 'X_umap'

In [6]:
f = '../data/P38_glut.h5ad'
adata2 = ad.read(f, backed='r+')
adata2

AnnData object with n_obs Ã— n_vars = 10485 Ã— 30869 backed at '../data/P38_glut.h5ad'
    obs: 'batch', 'n_genes', 'percent_mito', 'n_counts', 'leiden', 'Doublet', 'Doublet Score', 'cluster', 'Class_broad', 'sample', 'Age', 'subclass', 'layer', 'Type', 'Subclass'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'Type_colors', 'cluster_colors', "dendrogram_['leiden']", 'hvg', 'layer_colors', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'sample_colors', 'umap'
    obsm: 'X_harmony', 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [7]:
f = '../data/P38_glut_dr.h5ad'
adata3 = ad.read(f, backed='r+')
adata3

AnnData object with n_obs Ã— n_vars = 17499 Ã— 20354 backed at '../data/P38_glut_dr.h5ad'
    obs: 'n_genes', 'percent_mito', 'n_counts', 'Doublet', 'Doublet Score', 'batch', 'leiden', 'sample', 'cluster', 'Type', 'Subclass'
    var: 'gene_ids', 'feature_types', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'Subclass_colors', 'Type_colors', 'cluster_colors', "dendrogram_['leiden']", 'hvg', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'sample_colors', 'umap'
    obsm: 'X_harmony', 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

# Next
- all data 
- candidate genes: type A,B,C equal? best? can they classify A,B,C?
- MERFISH data?

In [8]:
adata2.obs

,batch,n_genes,percent_mito,n_counts,leiden,Doublet,Doublet Score,cluster,Class_broad,sample,Age,subclass,layer,Type,Subclass
AAACCCAAGTGACACG-1-P38_1a-P38,P38,2931,0.001048,8590.0,0,False,0.010833,L2/3_A,Excitatory,P38_1a,P38,L2/3,L2/3/4,L2/3_B,L2/3
AAACGCTAGTACAGAT-1-P38_1a-P38,P38,4451,0.000952,13659.0,6,False,0.061252,L4_A,Excitatory,P38_1a,P38,L4,L2/3/4,L4_C,L4
AAACGCTAGTGAGGCT-1-P38_1a-P38,P38,4543,0.001475,16269.0,6,False,0.048147,L4_A,Excitatory,P38_1a,P38,L4,L2/3/4,L4_C,L4
AAACGCTGTATGGAAT-1-P38_1a-P38,P38,2678,0.001813,6618.0,3,False,0.013447,L4_B,Excitatory,P38_1a,P38,L4,L2/3/4,L4_B,L4
AAAGAACAGTAGTCCT-1-P38_1a-P38,P38,3781,0.000159,12607.0,6,False,0.029642,L4_A,Excitatory,P38_1a,P38,L4,L2/3/4,L4_C,L4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTTGTTGCAGCCCAGT-1-P38_2b-P38,P38,3720,0.000601,11642.0,7,False,0.030005,L6CT_C,Excitatory,P38_2b,P38,L6CT,L5/6,L6CT_C,L6CT
TTTGTTGGTGTTATCG-1-P38_2b-P38,P38,3543,0.000446,8973.0,5,False,0.011412,L5IT,Excitatory,P38_2b,P38,L5IT,L5/6,L5IT,L5IT
TTTGTTGTCCATGATG-1-P38_2b-P38,P38,3990,0.000509,13761.0,0,False,0.040638,L2/3_A,Excitatory,P38_2b,P38,L2/3,L2/3/4,L2/3_B,L2/3
TTTGTTGTCGTAGAGG-1-P38_2b-P38,P38,4425,0.000409,14681.0,8,False,0.007687,L5PT_A,Excitatory,P38_2b,P38,L5PT,L5/6,L5PT_A,L5PT
TTTGTTGTCTCTCGCA-1-P38_2b-P38,P38,3719,0.000703,12803.0,2,False,0.021370,L6CT_B,Excitatory,P38_2b,P38,L6CT,L5/6,L6CT_B,L6CT

In [10]:
adata1.obs

,batch,n_genes,percent_mito,n_counts,leiden,Doublet,Doublet Score,cluster,Class_broad,sample,Age,subclass,sample_new,layer,Type,Subclass,AgeType,Condition
AACAAGACATGTCAGT-1-P28_1a-P28-P28_NR L2/3 A-0,0,3659,0.001551,10964.0,10,False,0.012605,L2/3_B,Excitatory,P28_1a,P28,L2/3,P28_1,L2/3/4,L2/3_A,L2/3,P28_NR L2/3 A,P28_NR
AACTTCTAGGTCGAGT-1-P28_1a-P28-P28_NR L2/3 A-0,0,4894,0.002779,15835.0,10,False,0.024988,L2/3_B,Excitatory,P28_1a,P28,L2/3,P28_1,L2/3/4,L2/3_A,L2/3,P28_NR L2/3 A,P28_NR
AAGCGTTAGTGAGTTA-1-P28_1a-P28-P28_NR L2/3 A-0,0,4102,0.002166,12925.0,10,False,0.038224,L2/3_B,Excitatory,P28_1a,P28,L2/3,P28_1,L2/3/4,L2/3_A,L2/3,P28_NR L2/3 A,P28_NR
AATGGCTGTAGCTTAC-1-P28_1a-P28-P28_NR L2/3 A-0,0,4576,0.000483,14501.0,10,False,0.019714,L2/3_B,Excitatory,P28_1a,P28,L2/3,P28_1,L2/3/4,L2/3_A,L2/3,P28_NR L2/3 A,P28_NR
ACACAGTCATTGACTG-1-P28_1a-P28-P28_NR L2/3 A-0,0,5249,0.001142,19264.0,10,False,0.030428,L2/3_B,Excitatory,P28_1a,P28,L2/3,P28_1,L2/3/4,L2/3_A,L2/3,P28_NR L2/3 A,P28_NR
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TTCACCGGTCGTGTTA-1-P28_dl_2b-4-P28_DL L2/3 3-4,4,3007,0.000989,8086.0,9,False,0.017544,NaN,NaN,P28_dl_2b,NaN,NaN,NaN,NaN,L2/3_3,L2/3,P28_DL L2/3 3,P28_DL
TTGAACGGTGTCTTCC-1-P28_dl_2b-4-P28_DL L2/3 3-4,4,3973,0.000218,13746.0,9,False,0.109474,NaN,NaN,P28_dl_2b,NaN,NaN,NaN,NaN,L2/3_3,L2/3,P28_DL L2/3 3,P28_DL
TTGATGGAGGCGAACT-1-P28_dl_2b-4-P28_DL L2/3 3-4,4,3477,0.000404,12364.0,9,False,0.063345,NaN,NaN,P28_dl_2b,NaN,NaN,NaN,NaN,L2/3_3,L2/3,P28_DL L2/3 3,P28_DL
TCACGGGTCCATGAGT-1-P28_dl_1b-7-P28_DL L2/3 3-4,4,6486,0.000056,35608.0,9,False,0.124563,NaN,NaN,P28_dl_1b,NaN,NaN,NaN,NaN,L2/3_3,L2/3,P28_DL L2/3 3,P28_DL
AGGGTGAAGACTCTTG-1-P28_dl_2b-7-P28_DL L2/3 3-4,4,6294,0.000126,31633.0,9,False,0.119190,NaN,NaN,P28_dl_2b,NaN,NaN,NaN,NaN,L2/3_3,L2/3,P28_DL L2/3 3,P28_DL

In [12]:
adata1.obs['sample'].value_counts().sort_index()

P28_1a       1050
P28_1b       1021
P28_2a        943
P28_2b       1030
P28_dl_1a    1238
P28_dl_1b    1129
P28_dl_2a    1134
P28_dl_2b    1158
P28_dr_1a     951
P28_dr_1b    1060
P28_dr_3a    1354
P28_dr_3b    1339
P38_1a        720
P38_2a       1023
P38_2b        954
P38_dr_1a    1333
P38_dr_1b    1093
P38_dr_2a    1309
P38_dr_2b    1430
Name: sample, dtype: int64

In [20]:
adata2.obs['sample'].value_counts().sort_index()

P38_1a    2600
P38_2a    4053
P38_2b    3832
Name: sample, dtype: int64

In [21]:
adata2.obs['cluster'].value_counts().sort_index()

L2/3_A    1971
L4_C      1280
L6CT_B     968
L4_B       955
L6IT_A     901
L4_A       784
L5IT       708
L6CT_C     642
L2/3_C     611
L5PT_A     510
L5NP       307
L2/3_B     236
L6CT_A     195
L6IT_B     184
L6b        141
L5PT_B      92
Name: cluster, dtype: int64

In [22]:
adata2.obs['Subclass'].value_counts().sort_index()

L2/3    2697
L4      3139
L5IT     701
L5NP     311
L5PT     600
L6CT    1806
L6IT    1092
L6b      139
Name: Subclass, dtype: int64

# get cluster mean

In [23]:
adata2

AnnData object with n_obs Ã— n_vars = 10485 Ã— 30869 backed at '../data/P38_glut.h5ad'
    obs: 'batch', 'n_genes', 'percent_mito', 'n_counts', 'leiden', 'Doublet', 'Doublet Score', 'cluster', 'Class_broad', 'sample', 'Age', 'subclass', 'layer', 'Type', 'Subclass'
    var: 'gene_ids', 'feature_types', 'n_cells', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'mean', 'std'
    uns: 'Type_colors', 'cluster_colors', "dendrogram_['leiden']", 'hvg', 'layer_colors', 'leiden', 'leiden_colors', 'neighbors', 'pca', 'sample_colors', 'umap'
    obsm: 'X_harmony', 'X_pca', 'X_umap'
    varm: 'PCs'
    obsp: 'connectivities', 'distances'

In [26]:
adata2.X

In [27]:
adata2.var

,gene_ids,feature_types,n_cells,highly_variable,means,dispersions,dispersions_norm,mean,std
Xkr4,ENSMUSG00000051951,Gene Expression,138701,False,2.291300,1.229770,0.001417,2.123416,0.623287
Gm18956,ENSMUSG00000102851,Gene Expression,63,False,0.000421,-0.032678,-0.668886,0.000297,0.013958
Gm1992,ENSMUSG00000089699,Gene Expression,36088,True,0.270936,0.309633,0.862929,0.192292,0.358851
Gm7341,ENSMUSG00000103147,Gene Expression,31,False,0.000158,0.505672,1.740191,0.000093,0.009547
Gm10568,ENSMUSG00000102348,Gene Expression,97,False,0.001049,0.196537,0.356833,0.000696,0.023020
...,...,...,...,...,...,...,...,...,...
AC125149.3,ENSMUSG00000079800,Gene Expression,211,False,0.001281,0.158913,0.188470,0.000870,0.024843
AC168977.1,ENSMUSG00000079808,Gene Expression,37,False,0.000137,0.364851,1.110028,0.000085,0.008712
AC149090.1,ENSMUSG00000095041,Gene Expression,131565,False,1.540500,0.870648,0.234861,1.316356,0.713866
CAAA01118383.1,ENSMUSG00000063897,Gene Expression,13356,False,0.056779,0.119782,0.013363,0.039328,0.164804
CAAA01147332.1,ENSMUSG00000095742,Gene Expression,420,False,0.005275,0.101519,-0.068367,0.003585,0.050883

In [35]:
%%time
genes = [
    'Cdh13', 
    'Trpc6',
    'Chrm2',
    'Gria3',
    'Whrn',
    'Baz1a',
    'Adamts2',
    'Kcna1',
    'Igfn1',
    'Epha3',
]
adata2[:,genes].write('/bigstore/GeneralStorage/fangming/visctx/P38_glut_10genes.h5ad')

CPU times: user 88.6 ms, sys: 15.1 s, total: 15.2 s
Wall time: 24.4 s